Repository bergsalex/roux-cs5500-haploqa, pull requests merged in 2021-12, with the labels that each got.

#40 Moving common svg component func into svg-element common component
  libs/ngx-genome-karyotype-plots/src/lib/genome-karyotype-plot/genome-karyotype-plot.component.html
  libs/ngx-genome-karyotype-plots/src/lib/ngx-genome-karyotype-plots.module.ts
  libs/ngx-genome-karyotype-plots/src/lib/svg-element/svg-element.component.html
  libs/ngx-genome-karyotype-plots/src/lib/svg-element/svg-element.component.scss
  libs/ngx-genome-karyotype-plots/src/lib/svg-element/svg-element.component.spec.ts
  libs/ngx-genome-karyotype-plots/src/lib/svg-element/svg-element.component.ts
Labels: User Story 4.1

#47 Replacing d3 dom manipulation with angular native
  libs/ngx-genome-karyotype-plots/src/lib/svg-element/svg-element.component.html
  libs/ngx-genome-karyotype-plots/src/lib/svg-element/svg-element.component.scss
  libs/ngx-genome-karyotype-plots/src/lib/svg-element/svg-element.component.spec.ts
  libs/ngx-genome-karyotype-plots/src/lib/svg-element/svg-element.component.ts
Labels: enhancement, User Story 4.1

#48 Adding static data for development
  libs/ngx-genome-karyotype-plots/src/lib/mm10-data.ts
  libs/ngx-genome-karyotype-plots/src/lib/static-data.ts
Labels: documentation, User Story 4.1

#49 Feature/add an svg tools service to hold common d3 dom manipulation code 45
  libs/ngx-genome-karyotype-plots/src/lib/chr-ids.service.ts
  libs/ngx-genome-karyotype-plots/src/lib/genome-karyotype-plot/genome-karyotype-plot.component.html
  libs/ngx-genome-karyotype-plots/src/lib/genome-karyotype-plot/genome-karyotype-plot.component.scss
  libs/ngx-genome-karyotype-plots/src/lib/genome-karyotype-plot/genome-karyotype-plot.component.spec.ts
  libs/ngx-genome-karyotype-plots/src/lib/genome-karyotype-plot/genome-karyotype-plot.component.ts
  libs/ngx-genome-karyotype-plots/src/lib/svg-tools.service.spec.ts
  libs/ngx-genome-karyotype-plots/src/lib/svg-tools.service.ts
  libs/ngx-genome-karyotype-plots/src/lib/zoom-interval.service.ts
Labels: User Story 4.1

#60 Adding readme with library usage information
  libs/ngx-genome-karyotype-plots/README.md
Labels: documentation, User Story 4.1

#61 Adding a strain map service
  libs/ngx-genome-karyotype-plots/src/lib/strain-map.service.spec.ts
  libs/ngx-genome-karyotype-plots/src/lib/strain-map.service.ts
Labels: enhancement, User Story 4.1

#64 Utility/multi issue branch dec 6
  libs/ngx-genome-karyotype-plots/src/index.ts
  libs/ngx-genome-karyotype-plots/src/lib/example-data/haplo_data_ADG.ts
  libs/ngx-genome-karyotype-plots/src/lib/example-data/mm10-data.ts
  libs/ngx-genome-karyotype-plots/src/lib/example-data/sample_34M.ts
  libs/ngx-genome-karyotype-plots/src/lib/example-data/sample_ADG.ts
  libs/ngx-genome-karyotype-plots/src/lib/example-data/snp_data_ADG_1.ts
  libs/ngx-genome-karyotype-plots/src/lib/genome-interval-plot/genome-interval-plot.component.html
  libs/ngx-genome-karyotype-plots/src/lib/genome-interval-plot/genome-interval-plot.component.ts
  libs/ngx-genome-karyotype-plots/src/lib/genome-karyotype-plot/genome-karyotype-plot.component.html
  libs/ngx-genome-karyotype-plots/src/lib/genome-karyotype-plot/genome-karyotype-plot.component.scss
  libs/ngx-genome-karyotype-plots/src/lib/genome-karyotype-plot/genome-karyotype-plot.component.ts
  libs/ngx-genome-karyotype-plots/src/lib/haplotypes-panel/haplotypes-panel.component.html
  libs/ngx-genome-karyotype-plots/src/lib/haplotypes-panel/haplotypes-panel.component.scss
  libs/ngx-genome-karyotype-plots/src/lib/haplotypes-panel/haplotypes-panel.component.spec.ts
  libs/ngx-genome-karyotype-plots/src/lib/haplotypes-panel/haplotypes-panel.component.ts
  libs/ngx-genome-karyotype-plots/src/lib/ngx-genome-karyotype-plots.module.ts
  libs/ngx-genome-karyotype-plots/src/lib/plot-container/plot-container.component.html
  libs/ngx-genome-karyotype-plots/src/lib/plot-container/plot-container.component.scss
  libs/ngx-genome-karyotype-plots/src/lib/plot-container/plot-container.component.spec.ts
  libs/ngx-genome-karyotype-plots/src/lib/plot-container/plot-container.component.ts
  libs/ngx-genome-karyotype-plots/src/lib/svg-element/svg-element.component.html
  libs/ngx-genome-karyotype-plots/src/lib/svg-element/svg-element.component.scss
  libs/ngx-genome-karyotype-plots/src/lib/svg-element/svg-element.component.ts
  libs/ngx-genome-karyotype-plots/src/lib/svg-tools.service.ts
  libs/ngx-genome-karyotype-plots/src/lib/zoom-interval.service.ts
Labels: enhancement, User Story 4.1

#62 Moving example data and adding ADG example
  libs/ngx-genome-karyotype-plots/src/index.ts
  libs/ngx-genome-karyotype-plots/src/lib/example-data/haplo_data_ADG.ts
  libs/ngx-genome-karyotype-plots/src/lib/example-data/mm10-data.ts
  libs/ngx-genome-karyotype-plots/src/lib/example-data/sample_34M.ts
  libs/ngx-genome-karyotype-plots/src/lib/example-data/sample_ADG.ts
  libs/ngx-genome-karyotype-plots/src/lib/example-data/snp_data_ADG_1.ts
Labels: documentation, enhancement, User Story 4.1

#63 implemented the haplotype strain panel
  libs/ngx-genome-karyotype-plots/src/lib/haplotypes-panel/haplotypes-panel.component.html
  libs/ngx-genome-karyotype-plots/src/lib/haplotypes-panel/haplotypes-panel.component.scss
  libs/ngx-genome-karyotype-plots/src/lib/haplotypes-panel/haplotypes-panel.component.spec.ts
  libs/ngx-genome-karyotype-plots/src/lib/haplotypes-panel/haplotypes-panel.component.ts
  libs/ngx-genome-karyotype-plots/src/lib/ngx-genome-karyotype-plots.module.ts
Labels: enhancement, User Story 4.1

#52 Feature/create a simple base application which uses the gkp components 50
  .gitignore
  angular.json
  apps/haplo-qa/jest.config.js
  apps/haplo-qa/src/app/app.component.html
  apps/haplo-qa/src/app/app.component.scss
  apps/haplo-qa/src/app/app.component.spec.ts
  apps/haplo-qa/src/app/app.component.ts
  apps/haplo-qa/src/app/app.module.ts
  apps/haplo-qa/src/jax-theme.scss
  apps/haplo-qa/src/styles.scss
  docs/ProcessModelSelection.md
  docs/design/SoftwareDesignDescription.md
  docs/testing/TestPlan.md
  libs/ngx-genome-karyotype-plots/src/lib/haplotypes-panel/haplotypes-panel.component.html
Labels: User Story 4.1

#67 Adding test plan
  docs/testing/TestPlan.md
Labels: documentation, User Story 4.1

#65 design document modify
  docs/.DS_Store
  docs/design/SoftwareDesignDescription.md
  docs/design/diagrams-of-features.png
Labels: documentation, User Story 4.1

#74 Task/add test results dec 12
  docs/SoftwareRequirementsSpecification.md
  docs/testing/TestPlan.md
  docs/testing/TestResults_dec_12_2021.md
Labels: documentation

#71 Improvements to design and use of chrIds service
  libs/ngx-genome-karyotype-plots/src/lib/chr-ids.service.ts
  libs/ngx-genome-karyotype-plots/src/lib/genome-interval-plot/genome-interval-plot.component.ts
  libs/ngx-genome-karyotype-plots/src/lib/haplotypes-panel/haplotypes-panel.component.html
  libs/ngx-genome-karyotype-plots/src/lib/plot-container/plot-container.component.ts
Labels: enhancement, User Story 4.1

#76 Adding complete project evaluation
  docs/CompleteProjectEvaluation_dec_13_2021.md
Labels: documentation

#72 Task/style consistency cleanup
  apps/haplo-qa/src/app/app.component.html
  apps/haplo-qa/src/app/app.component.spec.ts
  libs/ngx-genome-karyotype-plots/src/lib/chr-ids.service.ts
  libs/ngx-genome-karyotype-plots/src/lib/example-data/mm10-data.ts
  libs/ngx-genome-karyotype-plots/src/lib/example-data/sample_34M.ts
  libs/ngx-genome-karyotype-plots/src/lib/example-data/sample_ADG.ts
  libs/ngx-genome-karyotype-plots/src/lib/example-data/snp_data_ADG_1.ts
  libs/ngx-genome-karyotype-plots/src/lib/genome-interval-plot/genome-interval-plot.component.spec.ts
  libs/ngx-genome-karyotype-plots/src/lib/genome-interval-plot/genome-interval-plot.component.ts
  libs/ngx-genome-karyotype-plots/src/lib/genome-karyotype-plot/genome-karyotype-plot.component.html
  libs/ngx-genome-karyotype-plots/src/lib/genome-karyotype-plot/genome-karyotype-plot.component.ts
  libs/ngx-genome-karyotype-plots/src/lib/haplotypes-panel/haplotypes-panel.component.ts
  libs/ngx-genome-karyotype-plots/src/lib/plot-container/plot-container.component.ts
  libs/ngx-genome-karyotype-plots/src/lib/strain-map.service.ts
  libs/ngx-genome-karyotype-plots/src/lib/svg-element/svg-element.component.ts
  libs/ngx-genome-karyotype-plots/src/lib/svg-tools.service.ts
  libs/ngx-genome-karyotype-plots/src/lib/zoom-interval.service.ts
Labels: enhancement
